#!/usr/bin/env python3
"""Generate Z80 sprite data (data+mask, 16x16) from ASCII art.

Each sprite is 16 wide x 16 tall. In the art:
    'X' or '#'  -> solid pixel  (data bit 1, mask bit 0)
    anything else -> transparent (data bit 0, mask bit 1)

Output rows are emitted as 4 bytes per scan line:
    data_hi, data_lo, mask_hi, mask_lo
so the masked blitter can do:  screen = (screen AND mask) OR data
(after both are shifted together by the sub-cell x offset).
"""

SPRITES = {
# Player ship, pointing right (travel is left-to-right)
"spr_ship": [
    "................",
    ".....XX.........",
    ".....XXX........",
    "..X..XXXX.......",
    "..XXXXXXXXX.....",
    ".XXXXXXXXXXXX...",
    ".XXXXXXXXXXXXXX.",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    ".XXXXXXXXXXXXXX.",
    ".XXXXXXXXXXXX...",
    "..XXXXXXXXX.....",
    "..X..XXXX.......",
    ".....XXX........",
    ".....XX.........",
    "................",
],
# Asteroid / rock hazard
"spr_rock": [
    "................",
    "....XXXXXX......",
    "...XXXXXXXXX....",
    "..XXXXXXXXXXX...",
    ".XXXXXXX.XXXXX..",
    ".XXXXXX...XXXX..",
    "XXXXXXX..XXXXXX.",
    "XXXXXXXXXXXXXXX.",
    "XXXXX.XXXXXXXXX.",
    "XXXX...XXXXXXXX.",
    ".XXXX..XXXXXXX..",
    ".XXXXXXXXXXXXX..",
    "..XXXXXXXXXXX...",
    "...XXXXXXXXX....",
    "....XXXXXX......",
    "................",
],
# Enemy craft, pointing left (it flies toward the player)
"spr_enemy": [
    "................",
    ".........XX.....",
    "........XXX.....",
    ".......XXXX..X..",
    ".....XXXXXXXXX..",
    "...XXXXXXXXXXXX.",
    ".XXXXXXXXXXXXXX.",
    "XXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXX",
    ".XXXXXXXXXXXXXX.",
    "...XXXXXXXXXXXX.",
    ".....XXXXXXXXX..",
    ".......XXXX..X..",
    "........XXX.....",
    ".........XX.....",
    "................",
],
# Player bullet (short bright dash, centred vertically)
"spr_bullet": [
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "...XXXXXX.......",
    "...XXXXXX.......",
    "...XXXXXX.......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
],
# Collectible crystal
"spr_crystal": [
    "................",
    ".......XX.......",
    "......XXXX......",
    ".....XX..XX.....",
    "....XX....XX....",
    "...XX..XX..XX...",
    "..XX..XXXX..XX..",
    ".XX..XX..XX..XX.",
    ".XX..XX..XX..XX.",
    "..XX..XXXX..XX..",
    "...XX..XX..XX...",
    "....XX....XX....",
    ".....XX..XX.....",
    "......XXXX......",
    ".......XX.......",
    "................",
],
}


def row_bytes(line):
    line = (line + "................")[:16]
    data = 0
    for i, c in enumerate(line):
        if c in "X#":
            data |= 1 << (15 - i)
    mask = (~data) & 0xFFFF
    return (data >> 8) & 0xFF, data & 0xFF, (mask >> 8) & 0xFF, mask & 0xFF


def main():
    out = ["; Generated by tools/mksprites.py - do not edit by hand.",
           "; Layout per row: data_hi, data_lo, mask_hi, mask_lo", ""]
    for name, art in SPRITES.items():
        out.append(name + ":")
        for line in art:
            dh, dl, mh, ml = row_bytes(line)
            out.append("        db  %3d,%3d,%3d,%3d" % (dh, dl, mh, ml))
        out.append("")
    import os
    dest = os.path.join(os.path.dirname(__file__), "..", "src", "sprites.inc")
    dest = os.path.normpath(dest)
    open(dest, "w").write("\n".join(out))
    print("wrote %s (%d sprites)" % (dest, len(SPRITES)))


if __name__ == "__main__":
    main()
