#!/usr/bin/env python3
"""Generate 16x16 chess-piece glyph data (pieces.inc) from ASCII art.

Each piece is a 16x16 silhouette ('#' = ink pixel). The board draws every
square as a 2x2 character block, so a piece occupies four 8x8 cells. We emit
the bytes cell-by-cell in the order the renderer consumes them:
    top-left(8 rows) | top-right(8 rows) | bot-left(8 rows) | bot-right(8 rows)
so the draw routine can blast 8 bytes per cell with HL += 256 between rows.

Run:  python3 pieces.py > pieces.inc
"""

ART = {
"pawn": [
"                ",
"                ",
"                ",
"      ####      ",
"     ######     ",
"     ######     ",
"      ####      ",
"      ####      ",
"     ######     ",
"    ########    ",
"    ########    ",
"   ##########   ",
"  ############  ",
"  ############  ",
"                ",
"                ",
],
"knight": [
"                ",
"        ##      ",
"      #####     ",
"     #######    ",
"    ## ######   ",
"   #   #######  ",
"  ##  ########  ",
"     #########  ",
"    ##########  ",
"      ########  ",
"      ########  ",
"     #########  ",
"    ##########  ",
"   ###########  ",
"  ############# ",
"                ",
],
"bishop": [
"                ",
"       ##       ",
"      ####      ",
"     ##  ##     ",
"     ## # #     ",
"     ##### #    ",
"     ######     ",
"      ####      ",
"      ####      ",
"     ######     ",
"     ######     ",
"      ####      ",
"     ######     ",
"   ##########   ",
"  ############  ",
"                ",
],
"rook": [
"                ",
"   ## ## ## ##   ",
"   ###########  ",
"   ###########  ",
"    #########   ",
"     #######    ",
"     #######    ",
"     #######    ",
"     #######    ",
"     #######    ",
"     #######    ",
"    #########   ",
"   ###########  ",
"  #############  ",
"  #############  ",
"                ",
],
"queen": [
"                ",
"  #   #   #   #  ",
"  ## ### ### ##  ",
"  ## ### ### ##  ",
"   ###########  ",
"   ###########  ",
"    #########   ",
"    #########   ",
"     #######    ",
"     #######    ",
"    #########   ",
"   ###########  ",
"   ###########  ",
"  #############  ",
"  #############  ",
"                ",
],
"king": [
"       ##       ",
"       ##       ",
"     ######     ",
"       ##       ",
"      ####      ",
"     ######     ",
"    ########    ",
"   ##########   ",
"   ##########   ",
"    ########    ",
"     ######     ",
"     ######     ",
"    ########    ",
"   ##########   ",
"  ############  ",
"                ",
],
}

ORDER = ["pawn", "knight", "bishop", "rook", "queen", "king"]


def normalize(art):
    return [(line + " " * 16)[:16] for line in art]


def outline(art):
    """Hollow contour: keep a '#' only if it borders empty space (or the
    image edge).  Solid interiors clear out so the square colour shows
    through, giving white pieces a black keyline legible on any square."""
    g = normalize(art)
    out = []
    for y in range(16):
        row = []
        for x in range(16):
            if g[y][x] != '#':
                row.append(' ')
                continue
            edge = False
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = x + dx, y + dy
                if not (0 <= nx < 16 and 0 <= ny < 16) or g[ny][nx] != '#':
                    edge = True
                    break
            row.append('#' if edge else ' ')
        out.append("".join(row))
    return out


def rows_to_bytes(art):
    # returns (left_col_bytes[16], right_col_bytes[16])
    left, right = [], []
    for line in normalize(art):
        l = sum((1 << (7 - i)) for i in range(8) if line[i] == '#')
        r = sum((1 << (7 - i)) for i in range(8) if line[8 + i] == '#')
        left.append(l)
        right.append(r)
    return left, right


def emit(label, transform):
    print(f"{label}:")
    for name in ORDER:
        left, right = rows_to_bytes(transform(ART[name]))
        cells = [
            ("TL", left[0:8]), ("TR", right[0:8]),
            ("BL", left[8:16]), ("BR", right[8:16]),
        ]
        print(f"; --- {name} ---")
        for tag, bytes8 in cells:
            row = ",".join(f"${b:02X}" for b in bytes8)
            print(f"    defb {row}   ; {name} {tag}")


def main():
    print("; pieces.inc - generated by pieces.py, do not edit by hand")
    print("; 6 pieces x 32 bytes; cell order TL,TR,BL,BR (8 bytes each)")
    print("; glyphs  = solid silhouette (black pieces)")
    print("; glyphsW = hollow outline   (white pieces; black keyline)")
    emit("glyphs", lambda a: a)
    emit("glyphsW", outline)


if __name__ == "__main__":
    main()
