#!/usr/bin/env python3
"""Generate 16x16 chess-piece glyph data (pieces.inc) from ASCII art.

Each piece is a 16x16 silhouette ('#' = ink pixel). The board draws every
square as a 2x2 character block, so a piece occupies four 8x8 cells. We emit
the bytes cell-by-cell in the order the renderer consumes them:
    top-left(8 rows) | top-right(8 rows) | bot-left(8 rows) | bot-right(8 rows)
so the draw routine can blast 8 bytes per cell with HL += 256 between rows.

Run:  python3 pieces.py > pieces.inc
"""

ART = {
"pawn": [
"                ",
"                ",
"                ",
"      ####      ",
"     ######     ",
"     ######     ",
"      ####      ",
"      ####      ",
"     ######     ",
"    ########    ",
"    ########    ",
"   ##########   ",
"  ############  ",
"  ############  ",
"                ",
"                ",
],
"knight": [
"                ",
"        ##      ",
"      #####     ",
"     #######    ",
"    ## ######   ",
"   #   #######  ",
"  ##  ########  ",
"     #########  ",
"    ##########  ",
"      ########  ",
"      ########  ",
"     #########  ",
"    ##########  ",
"   ###########  ",
"  ############# ",
"                ",
],
"bishop": [
"                ",
"       ##       ",
"      ####      ",
"     ##  ##     ",
"     ## # #     ",
"     ##### #    ",
"     ######     ",
"      ####      ",
"      ####      ",
"     ######     ",
"     ######     ",
"      ####      ",
"     ######     ",
"   ##########   ",
"  ############  ",
"                ",
],
"rook": [
"                ",
"   ## ## ## ##   ",
"   ###########  ",
"   ###########  ",
"    #########   ",
"     #######    ",
"     #######    ",
"     #######    ",
"     #######    ",
"     #######    ",
"     #######    ",
"    #########   ",
"   ###########  ",
"  #############  ",
"  #############  ",
"                ",
],
"queen": [
"                ",
"  #   #   #   #  ",
"  ## ### ### ##  ",
"  ## ### ### ##  ",
"   ###########  ",
"   ###########  ",
"    #########   ",
"    #########   ",
"     #######    ",
"     #######    ",
"    #########   ",
"   ###########  ",
"   ###########  ",
"  #############  ",
"  #############  ",
"                ",
],
"king": [
"       ##       ",
"       ##       ",
"     ######     ",
"       ##       ",
"      ####      ",
"     ######     ",
"    ########    ",
"   ##########   ",
"   ##########   ",
"    ########    ",
"     ######     ",
"     ######     ",
"    ########    ",
"   ##########   ",
"  ############  ",
"                ",
],
}

ORDER = ["pawn", "knight", "bishop", "rook", "queen", "king"]


def rows_to_bytes(art):
    # returns (left_col_bytes[16], right_col_bytes[16])
    left, right = [], []
    for line in art:
        line = (line + " " * 16)[:16]
        l = sum((1 << (7 - i)) for i in range(8) if line[i] == '#')
        r = sum((1 << (7 - i)) for i in range(8) if line[8 + i] == '#')
        left.append(l)
        right.append(r)
    return left, right


def main():
    print("; pieces.inc - generated by pieces.py, do not edit by hand")
    print("; 6 pieces x 32 bytes; cell order TL,TR,BL,BR (8 bytes each)")
    print("glyphs:")
    for name in ORDER:
        left, right = rows_to_bytes(ART[name])
        cells = [
            ("TL", left[0:8]), ("TR", right[0:8]),
            ("BL", left[8:16]), ("BR", right[8:16]),
        ]
        print(f"; --- {name} ---")
        for tag, bytes8 in cells:
            row = ",".join(f"${b:02X}" for b in bytes8)
            print(f"    defb {row}   ; {name} {tag}")


if __name__ == "__main__":
    main()
